# Name: Winter Sager
# Email: wrs9226@g.rit.edu
# Date: 02.04.26

#  The purpose of this Ansible script is to install and configure OpenLDAP.
#  The script has used LDAP features to implement 3 features; Creating Admin Groups, Adding Users to Groups and Place a File

---
-  name: Install/Configure OpenLDAP
   hosts: openldap
   become: yes
   tasks:

   # This next step will install OpenLDAP with the OpenLDAP server and LDAP tools. The update cache acts as sudo apt update.
   - name: Install OpenLDAP
     apt: 
       name:
         - slapd
         - ldap-utils
       update_cache: yes

   # This section copies the contents of base.ldif to create the Base structure for LDAP.
   - name: Copy Base File
     copy:
       src: base.ldif 
       dest: /tmp/base.ldif

   # This section takes the copied base file and adds it to LDAP, essential creating the LDAP structure.
   # The command ldapadd adds everything into the LDAP system. 
   # -x specifies just password and username and -D indicates the admin user.
   - name: Create Base LDAP structure
     command: ldapadd -x -D "cn=admin,dc=example,dc=com" -w adminpass -f /tmp/base.ldif
     

---
- name: Simple OpenLDAP installation
  hosts: ldap
  become: yes

  vars_files:
    - vars/ldap.yml

  tasks:

    # This task sets the password for config so it does not give you an invalid credential error everytime. 
    - name: Set admin password for cn=config
      copy:
        dest: /tmp/set_config_pw.ldif
        content: |
          dn: olcDatabase={0}config,cn=config
          changetype: modify
          replace: olcRootPW
          olcRootPW: {{ ldap_admin_password }}

    # This will apply the password to 
    - name: Apply cn=config password
      command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/set_config_pw.ldif

    # ---------------------------------------------------
    # 2. Configure main MDB database (suffix + admin)
    # ---------------------------------------------------
    - name: Configure main MDB database
      copy:
        dest: /tmp/configure_mdb.ldif
        content: |
          dn: olcDatabase={1}mdb,cn=config






---
-  name: Create LDAP Group with AD
   hosts: windows_ldap
   tasks:

  # This setup is used to create an Admin Group with LDAP for users who need total access
   - name: Create LDAP Admin Group
     ansible.windows.win_domain_group:
       name: Admins # Replace with group name
       scope: global
       category: security
       state: present
   
  # The following is used to add User to the Admin Group just created
   - name: Put Users In Group
     ansible.windows.win_domain_user:
       name: admin1 # Replace with real username
       groups:
         - Admins
       state: present


   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   - name: Create users
     ansible.windows.win_domain_user:
     name: jdoe
     password: "UserPass123!"
     groups:
      - "Domain Users"
---
- name: Setup Active Directory (LDAP on Windows)
  hosts: windows_ldap
  gather_facts: no

  tasks:

    - name: Install AD Domain Services
      ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes

    - name: Promote server to Domain Controller
      ansible.windows.win_domain:
        dns_domain_name: corp.local
        safe_mode_password: "RestorePass123!"
      register: domain_state

    - name: Reboot after promotion
      ansible.windows.win_reboot:
      when: domain_state.reboot_required
