---
- name: Deploy Nginx Container
  hosts: webservers
  become: yes
  tasks: 

    - name: Install Docker
      apt: 
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker Service
      service: 
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Python Module
      apt: 
        name: python3-docker
        state: present

    - name: Pull Nginx Image
      docker_image: 
        name: nginx
        tag: latest
        source: pull

    - name: Run Nginx Container
      docker_container: 
        name: nginx_container
        image: nginx:latest
        state: started
        restart_policy: always
        ports: 
          - "80:80"


