---
# Name: Caroline Richards
# Email: cpr9499@rit.edu
# Date: February 4, 2026
# Assignment: CDT HW 2

# This playbook deploys a web stack using Docker containers for Nginx, MySQL, and PHP
# REQUIRED FILES: 
# - nginx.conf : custom nginx configuration file
# - Dockerfile.php : Dockerfile to build custom PHP image with MySQL support
# - index.php  : custom webpage file
# - init.sql   : SQL database initialization script

# GREYTEAM NOTE: index.php and init.sql should be customized to fit the competition theme

- name: Deploy Nginx + MySQL + PHP Stack with Docker
  hosts: webservers
  become: yes
  tasks: 

    - name: Install Docker
      apt: 
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Python Module # SDK is required for Ansible's Docker modules to function 
      apt: 
        name: python3-docker
        state: present
  
    - name: Start Docker Service
      service: 
        name: docker
        state: started
        enabled: yes

    - name: Create Docker Network
      docker_network: 
        name: webnet # web stack containers will communicate over this network
        state: present

    - name: Create Web Directory # necessary files will be copied here
      file: 
        path: /opt/web
        state: directory

    - name: Copy Files # I am so happy Ansible has loops...
      copy: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: 
        - { src: 'index.php', dest: '/opt/web/index.php' }
        - { src: 'nginx.conf', dest: '/opt/web/nginx.conf' }
        - { src: 'init.sql', dest: '/opt/web/init.sql' }
        - { src: 'Dockerfile.php', dest: '/opt/web/Dockerfile' }

    - name: Run MySQL Container
      docker_container: 
        name: mysql
        image: mysql:latest
        state: started
        restart_policy: always # enable auto-restart on reboot
        env: 
          MYSQL_ROOT_PASSWORD: examplepassword
        volumes: 
          - /opt/web/init.sql:/docker-entrypoint-initdb.d/init.sql # initialize database with script
        networks: 
          - name: webnet

    - name: Create PHP Image w/ MySQL # need mysqli on php image, so will have to build a custom image with Dockerfile
      docker_image: 
        name: custom-php
        source: build
        build:
          path: /opt/web

    - name: Run PHP Container
      docker_container: 
        name: php
        image: custom-php
        state: started
        restart_policy: always
        volumes:
          - /opt/web:/var/www/html
        networks: 
          - name: webnet

    - name: Run Nginx Container
      docker_container: 
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports: 
          - "80:80"
        volumes: 
          - /opt/web:/var/www/html 
          - /opt/web/nginx.conf:/etc/nginx/conf.d/default.conf # use custom nginx config with php setup
        networks: 
        - name: webnet